---
apiVersion: v1
kind: Namespace
metadata:
  name: tools


---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: Namespace
metadata:
  name: logging

---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard


---
apiVersion: v1
kind: Namespace
metadata:
  name: development


---
apiVersion: v1
kind: Namespace
metadata:
  name: staging


---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  
