apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowdag
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: airflow-dags
  nfs:
    path: /mnt/airdags
    server: "SERVER_IP"
    readOnly: false


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowlog
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: logs-airflow-worker-0
  nfs:
    path: /mnt/airlogs
    server: "SERVER_IP"
    readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowtoolconnectors
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: airflowtoolconnectors
  nfs:
    path: /mnt/airConnectors
    server: "SERVER_IP"
    readOnly: false


---    

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowtoolcsv
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: airflowtoolcsv
  nfs:
    path: /mnt/aircsv
    server: "SERVER_IP"
    readOnly: false


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowtoolspark
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: airflowtoolspark
  nfs:
    path: /mnt/spark
    server: "SERVER_IP"
    readOnly: false


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowtooltrinocatalogs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: airflowtooltrinocatlog
  nfs:
    path: /mnt/catalogs
    server: "SERVER_IP"
    readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowtooltrinocatalogsbkp
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: airflowtooltrinocatlogbkp
  nfs:
    path: /mnt/catalogsbkp
    server: "SERVER_IP"
    readOnly: false


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowtoolhelm
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: airflowtoolhelm
  nfs:
    path: /mnt/helm
    server: "SERVER_IP"
    readOnly: false    


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowtoolexecutables
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: airflowtoolexecutables
  nfs:
    path: /mnt/sparkexecutables
    server: "SERVER_IP"
    readOnly: false


