- name: Installing secret
  hosts: master1
  become: yes
  become_user: ec2-user
  vars_files: 
    - ../tool_installation/vars.yaml
  tasks:

    - name: copy directory
      copy:
        src: ../secrets
        dest: /tmp/

    - name: create namespace
      command: kubectl create ns "{{ item }}"
      ignore_errors: yes      
      with_items: "{{ namespaces }}"


    - name: Run shell script
      command: kubectl create secret docker-registry {{ docker_secret_name }} --docker-username={{ docker_username }} --docker-password={{ docker_password }} --docker-server={{ docker_registry }} --namespace="{{ item }}"
      ignore_errors: yes
      with_items: "{{ namespaces }}"
