- name: Installing mysql
  hosts: master1
  become: yes
  become_user: ec2-user
  vars_files:
    - vars.yaml
  tasks:
    - name: copy directory
      copy:
        src: ../mysql
        dest: /tmp/
   
    - name: add namespace
      command: kubectl apply -f /tmp/mysql/namespace.yaml
      ignore_errors: yes

    - name: Run shell script
      script: script.sh {{ namespace }} {{ server_ip }} {{ image }} {{ secret }}

    - name: Apply Manifests
      command: kubectl apply -f /tmp/mysql/manifests/ -n {{ namespace }}
      ignore_errors: yes

