# grafana deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: test
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          # fsGroup: 2000
          privileged: true        
        ports:
        - name: grafana
          containerPort: 3000
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: nfspvc-grafana
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
       
      imagePullSecrets:
      - name: test

