apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowtoolconnectors
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: local-storage
  claimRef:
     namespace: tools
     name: airflowtoolconnectors
  nfs:
    path: /mnt/airConnectors
    server: 172.31.19.79
    readOnly: false
