apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowtoolcsv
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
     namespace: tools
     name: airflowtoolcsv
  nfs:
    path: /mnt/aircsv
    server: 172.31.19.79
    readOnly: false

