apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
     name: prometheus-server
     #namespace: tools
  nfs:
    path: /mnt/promdata
    server: "SERVER_IP"
    readOnly: false






