apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalogs-create
  #namespace: staging
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage    
  resources:
     requests:
       storage: 7Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airconnectors
  #namespace: staging
spec:
  accessModes:
  - ReadWriteMany
 #storageClassName: local-storage    
  resources:
     requests:
       storage: 5Gi
       
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aircsv
  #namespace: staging
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage    
  resources:
     requests:
       storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dags
  #namespace: staging
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage    
  resources:
     requests:
       storage: 5Gi
 
---       
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm
  #namespace: staging
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage    
  resources:
     requests:
       storage: 7Gi
       

---       
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinot-data-create
  #namespace: staging
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage    
  resources:
     requests:
       storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinot-data-yaml-create
  #namespace: staging
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  resources:
     requests:
       storage: 5Gi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark
  #namespace: staging
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage    
  resources:
     requests:
       storage: 5Gi
       
---              
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload
  #namespace: staging
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage    
  resources:
     requests:
       storage: 8Gi
