apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinot-data
  #namespace: development
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 4Gi
  storageClassName: local-storage
