apiVersion: v1
kind: PersistentVolume
metadata:
  name: pinot-data-yaml
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
     namespace: NAMESPACE
     name: pinot-data-yaml
  nfs:
    path: /mnt/pinot-data-yaml
    server: "SERVER_IP"
    readOnly: false
