apiVersion: batch/v1
kind: Job
metadata:
  name: pinot-realtime-quickstart-load-data-into-kafka
  namespace: development
spec:
  template:
    spec:
      containers:
        - name: loading-json-data-to-kafka
          image: bitnami/kafka
          #args: [ "StreamAvroIntoKafka", "-avroFile", "examples/stream/airlineStats/rawdata/airlineStats_data.avro", "-kafkaTopic", "flights-realtime", "-kafkaBrokerList", "kafka:9092", "-zkAddress", "kafka-zookeeper:2181" ]
          args: ["/opt/bitnami/kafka/data/movies.json", "kafka-console-producer.sh", "bootstrap-server", "kafka-0:9092" ]
      restartPolicy: OnFailure
  backoffLimit: 3

