apiVersion: v1
kind: PersistentVolume
metadata:
  name: pinot-server
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: data-pinot-server-0
  nfs:
    path: /mnt/pinot-server
    server: "SERVER_IP"
    readOnly: false

