apiVersion: v1
kind: PersistentVolume
metadata:
  name: pinot-zookeeper
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: data-pinot-zookeeper-0
  nfs:
    path: /mnt/pinot-zookeeper
    server: "SERVER_IP"
    readOnly: false

