---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: tools
  labels:
    app: minio-svc
spec:
  type: NodePort
  ports:
   - name: api
     port: 9000
     nodePort: 30625
     protocol: TCP
     targetPort: 9000
   - name: ui
     port: 9090
     protocol: TCP
     nodePort: 32005
     targetPort: 9090
  selector:
   app: minio
