apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowtoolconnectors
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: airflowtoolconnectors
  nfs:
    path: /mnt/airConnectors
    server: "SERVER_IP"
    readOnly: false
