apiVersion: v1
kind: PersistentVolume
metadata:
  name: catalogs
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: catalogs
  nfs:
    path: /mnt/catalogs
    server: "SERVER_IP"
    readOnly: false
