apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalogs
  #namespace: "NAMESPACE" 
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 4Gi
  storageClassName: local-storage
