apiVersion: v1
kind: PersistentVolume
metadata:
  name: trino-volume
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: trino-volume-pvc
  nfs:
    path: /mnt/trinovolume
    server: "SERVER_IP"
    readOnly: false
