apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowtoolconnectors
spec:
  accessModes:
  - ReadWriteMany
 #storageClassName: local-storage    
  resources:
     requests:
       storage: 5Gi
