apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowtoolcsv
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: airflowtoolcsv
  nfs:
    path: /mnt/aircsv
    server: "SERVER_IP"
    readOnly: false

