apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowtoolcsv
spec:
  accessModes:
  - ReadWriteMany
  resources:        
     requests:
       storage: 4Gi
  storageClassName: local-storage

