apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowtoolconnectors
spec:
  accessModes:
  - ReadWriteMany
 #storageClassName: local-storage    
  resources:
     requests:
       storage: 5Gi

---       
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowtoolcsv
spec:
  accessModes:
  - ReadWriteMany
  resources:        
     requests:
       storage: 4Gi
  storageClassName: local-storage


---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowtoolspark
spec:
  accessModes:
  - ReadWriteMany
 #storageClassName: local-storage
  resources:
     requests:
       storage: 5Gi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowtooltrinocatlog
spec:
  accessModes:
  - ReadWriteMany
 #storageClassName: local-storage
  resources:
     requests:
       storage: 5Gi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowtooltrinocatlogbkp
spec:
  accessModes:
  - ReadWriteMany
 #storageClassName: local-storage
  resources:
     requests:
       storage: 5Gi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowtoolhelm
spec:
  accessModes:
  - ReadWriteMany
 #storageClassName: local-storage
  resources:
     requests:
       storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowtoolexecutables
spec:
  accessModes:
  - ReadWriteMany
 #storageClassName: local-storage
  resources:
     requests:
       storage: 5Gi
       
