apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowtoolspark
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: local-storage
  claimRef:
     namespace: "NAMESPACE"
     name: airflowtoolspark
  nfs:
    path: /mnt/spark
    server: "SERVER_IP"
    readOnly: false


