apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowtoolspark
  namespace: tools
spec:
  accessModes:
  - ReadWriteMany
 #storageClassName: local-storage    
  resources:
     requests:
       storage: 5Gi
