apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  claimRef:
     namespace: "NAMESPACE"
     name: opensearch-cluster-master-opensearch-cluster-master-0
  nfs:
    path: /mnt/opensearch
    server: SERVER_IP
    readOnly: false

