apiVersion: v1
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICAgICAiZ2l0bGFiLnBhc3Npb25ieXRlcy5pbzo1MDUwIjogewogICAgICAgICAgICAgICAgICAgICJhdXRoIjogImFXNWtjbUZxWldWME9rOXdOVFl0TVRJOU5EUT0iCiAgICAgICAgICAgIH0KICAgIH0KfQo=

kind: Secret
metadata:
  name: registry
  namespace: elk
type: kubernetes.io/dockerconfigjson




