apiVersion: v1
kind: PersistentVolume
metadata:
  name: panoiq-file-storage
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    kind: PersistentVolumeClaim
    name: pvc-panoiq-file-storage
    namespace: NAMESPACE
  nfs:
    path: /mnt/fileStorageDevelopment
    server: SERVER_IP
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: discovery-lab-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  nfs:
    path: /mnt/certs
    server: SERVER_IP
