- name: Copying kubeconfig
  hosts: master1
  become: yes
  become_user: ec2-user
  tasks:
    - name: copy directory
      fetch:
        src: /home/ec2-user/.kube/config
        dest: /mnt/helm/kubeconfig.conf
        flat: yes
        recurse: yes
      #with_items: "{{ kubeadm_init.txt }}" 
               
